type LanguageMapType = {
    [ext: string]: string
}

export const LanguageMap: LanguageMapType = {
    "asm": "assembly",
    "bat": "bat",
    "c": "c",
    "coffee": "coffeescript",
    "cpp": "cpp",
    "cs": "csharp",
    "css": "css",
    "dart": "dart",
    "dockerfile": "dockerfile",
    "ejs": "ejs",
    "go": "go",
    "h": "c",
    "html": "html",
    "java": "java",
    "js": "javascript",
    "json": "json",
    "jsp": "java server pages",
    "jsx": "jsx",
    "kt": "kotlin",
    "lua": "lua",
    "m": "objective-c",
    "matlab": "matlab",
    "md": "markdown",
    "php": "php",
    "pl": "perl",
    "ps1": "powershell",
    "py": "python",
    "r": "r",
    "rb": "ruby",
    "rust": "rust",
    "scala": "scala",
    "scss": "scss",
    "sh": "bash",
    "sql": "sql",
    "svelte": "svelte",
    "swift": "swift",
    "ts": "typescript",
    "tsx": "tsx",
    "vue": "vue",
    "xml": "xml",
    "yml": "yaml",
}

